defaults:
  - base_model_config

model_name: "GritLM-7B"
model_class: causal_lm
load_from_shared: False
hf_model_id: "GritLM/GritLM-7B"

# MODEL PARAMETERS
max_input_length: 16000

d_model_name: "hidden_size"
final_layer_idx: -1

# STRUCTURE INFUSION
# Position embeddings
pe_init_std: 0

# Extraction
extraction_weight: 0.5
use_extraction_loss_weights: False

# TRAINING PARAMETERS
max_steps: 3750
val_check_interval: 1000  # seen instances, not steps!

batch_size: 1
accumulate_grad_batches: 8
learning_rate: 1e-4

# Tokenizer adds <s> in the beginning automatically
prompt_template_without_example: |-
  <|user|>
  Task: {task_explanation}
  Answer format: {format_explanation}
  {task_input}
  {task_explanation}
  {format_explanation}
  <|assistant|>
prompt_template_with_example: |-
  <|user|>
  Task: {task_explanation}
  Answer format: {format_explanation}
  {example}
  <|user|>
  {task_input}
  <|assistant|>
prompt_template_training: |-
  <|user|>
  {task_explanation}
  {task_input}
  <|assistant|>
example_template: |-
  <|user|>
  {task_input}
  <|assistant|>
  {answer}</s>

# Model generation should end with </s>

# LORA
use_lora: True
lora_r: 64
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
  - "q_proj"
  - "v_proj"