defaults:
  - base_model_config

model_name: "vicuna-7b-v1.5-16K"
model_class: causal_lm
load_from_shared: False
hf_model_id: "lmsys/vicuna-7b-v1.5-16k"

# MODEL PARAMETERS
max_input_length: 16000 # 8K on 48gb

d_model_name: "hidden_size"
final_layer_idx: -1

# STRUCTURE INFUSION
# Position embeddings
pe_init_std: 0

# Extraction
extraction_weight: 0.5
use_extraction_loss_weights: False

# TRAINING PARAMETERS
max_steps: 3750
val_check_interval: 1000

batch_size: 1
accumulate_grad_batches: 8
learning_rate: 1e-4

prompt_template_without_example: |-
  USER: Task: {task_explanation} 
  Answer format: {format_explanation}
  {task_input}
  {task_explanation}
  {format_explanation}
  ASSISTANT:
prompt_template_with_example: |-
  USER: Task: {task_explanation} 
  Answer format: {format_explanation}
  {example}
  USER: {task_input}
  ASSISTANT:
prompt_template_training: |-
  USER: {task_explanation}
  {task_input}
  ASSISTANT:
example_template: |-
  USER: {task_input}
  ASSISTANT: {answer}</s>

# LORA
use_lora: True
lora_r: 64
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
  - "q_proj"
  - "v_proj"